import { createFileRoute } from "@tanstack/react-router";
import { Check, X } from "lucide-react";
import { ContactBand, SiteShell } from "@/components/site-shell";
import { steps } from "@/lib/site-data";

export const Route=createFileRoute("/company")({head:()=>({meta:[{title:"회사 소개 — 이음앤빌드"},{name:"description",content:"이음앤빌드 회사 개요, 직통 계약 구조, 공동대표 리더십, 독점 권한과 업무 프로세스를 소개합니다."},{property:"og:title",content:"회사 소개 — 이음앤빌드"},{property:"og:description",content:"중국 본사와 직접 결정하고 한국 법인이 직접 책임지는 구조"},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Company});
function Company(){return <SiteShell>
  <section className="bg-foreground pt-20 text-background"><div className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10 lg:py-36"><p className="eyebrow text-primary-foreground/55">COMPANY · EXCLUSIVE REGIONAL HQ</p><h1 className="mt-7 max-w-5xl text-5xl font-semibold leading-tight md:text-7xl">한국 법인이 직접 계약하고<br/><span className="text-primary-foreground">직접 책임집니다.</span></h1><p className="mt-8 max-w-3xl text-base leading-8 text-background/65">중국 본사와 한국 발주처를 이어주는 창구가 아닙니다. 6개 기업의 상업 권한을 위임받아 직접 집행하며 계약, 세금계산서, 하자 책임이 모두 이 법인에서 나옵니다.</p></div></section>
  <section className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-primary">COMPANY FACT SHEET</p><h2 className="mt-5 text-4xl font-semibold">이음앤빌드</h2></div><dl className="fact-list">{[['법인명','주식회사 이음앤빌드'],['영문 상호','EUM&BUILD Co., Ltd.'],['공동대표이사','YIN XIUYING · 조준우'],['법인등록번호','110111-0968258'],['사업자등록번호','810-87-04122'],['본점 소재지','서울특별시 강남구 테헤란로 329, 삼흥빌딩 1612호 (역삼동)']].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></div><p className="mt-7 text-xs text-muted-foreground">사업자등록증 및 법인인감증명서 사본은 요청 시 제공합니다.</p></section>
  <section className="bg-muted"><div className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><p className="eyebrow text-primary">BUSINESS AREAS</p><h2 className="mt-5 text-4xl font-semibold md:text-5xl">자재만 넘기고 끝내지 않습니다.</h2><div className="mt-14 grid gap-px bg-border md:grid-cols-3">{[['MATERIAL SOURCING','건축자재 조달 · 유통','6개 본사의 생산 라인에서 직접 물량을 배정받고, 사양 개발과 샘플 대응까지 포함합니다.'],['BUSINESS CONSULTING','한중 사업 컨설팅','양국 시장 진출, 합작 구조와 계약 조건, 현지 파트너 검증을 지원합니다.'],['WORKFORCE OPERATION','프로젝트 인력 운영','석재 시공 전문 인력을 프로젝트 단위로 편성해 자재와 시공을 함께 책임집니다.']].map(([e,t,b])=><article key={e} className="bg-background p-8"><span className="eyebrow text-primary">{e}</span><h3 className="mt-8 text-2xl font-semibold">{t}</h3><p className="mt-5 text-sm leading-7 text-muted-foreground">{b}</p></article>)}</div><div className="mt-12 grid gap-6 md:grid-cols-4">{[['건설사 · 시공사','외장재 물량과 납기'],['설계 · 인테리어','사양·샘플·특수 마감'],['디벨로퍼','원가와 공정 일정 설계'],['자재 유통사','안정적인 지속 공급선']].map(([t,b])=><div key={t}><b>{t}</b><p className="mt-2 text-sm text-muted-foreground">{b}</p></div>)}</div></div></section>
  <section className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-primary">WHY EUM&amp;BUILD</p><h2 className="mt-5 text-4xl font-semibold">직통 구조의 차이</h2></div><div className="overflow-x-auto"><table className="comparison"><thead><tr><th>구분</th><th>일반 무역상 · 에이전트</th><th>이음앤빌드</th></tr></thead><tbody>{[['의사결정 속도','본사 회신 소요','협의 자리에서 즉시 확정'],['가격 구조','단계마다 마진 가산','본사 직결 단일 마진'],['책임 소재','본사와 중개상 사이 분산','한국 법인이 직접 부담']].map(r=><tr key={r[0]}>{r.map((c,i)=><td key={c}>{i===1?<><X size={14}/>{c}</>:i===2?<><Check size={14}/><b>{c}</b></>:c}</td>)}</tr>)}</tbody></table></div></div></section>
  <section className="bg-foreground text-background"><div className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><p className="eyebrow text-primary-foreground/55">EXECUTIVE LEADERSHIP</p><h2 className="mt-5 text-4xl font-semibold md:text-6xl">중국과 한국, 두 대표가 함께 결정합니다.</h2><div className="mt-16 grid gap-px bg-background/20 lg:grid-cols-2">{[{role:'CHINA ASSET & PARTNERSHIP',name:'YIN XIUYING',quote:'중국 거대 기업의 자산을 직접 움직이는 현지 파이프라인',items:['6개 핵심 기업 본사 직통 의사결정','자산·브랜드·생산 인프라 한국 직결','물량·생산·사양 변경 본사 협의 전권']},{role:'KOREA BUSINESS & EXECUTION',name:'조준우',quote:'한국 상업 시장을 관통하는 전략과 실행',items:['국내 사업화·유통·현지화 총괄','건설사·시공사·설계사 계약 설계','통관·물류·현장 대응 실행 전반']}].map(p=><article key={p.name} className="bg-foreground p-8 lg:p-12"><p className="eyebrow text-primary-foreground/55">{p.role}</p><h3 className="mt-8 text-4xl font-semibold">{p.name}</h3><p className="mt-2 text-sm text-background/45">공동대표이사 · Co-CEO</p><blockquote className="my-9 border-l border-primary pl-5 text-xl leading-8">“{p.quote}”</blockquote>{p.items.map(i=><p key={i} className="border-t border-background/15 py-4 text-sm text-background/65">{i}</p>)}</article>)}</div></div></section>
  <section className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><p className="eyebrow text-primary">OUR EXCLUSIVE AUTHORITY</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold md:text-5xl">직접 계약하고, 독점 운용하고, 함께 개발합니다.</h2><div className="mt-14 grid gap-px bg-border md:grid-cols-3">{[['01','본사 직통 계약','단가와 사양, 납기가 한 단계에서 확정되며 중간 마진이 존재하지 않습니다.'],['02','한국 내 독점 운용','6개 기업 자산의 국내 사업 운용권을 행사해 국내 경쟁 견적이 발생하지 않습니다.'],['03','공동 개발 · 투자','자재 공급을 넘어 한중 프로젝트의 개발과 투자 의사결정에 참여합니다.']].map(([n,t,b])=><article key={n} className="bg-background p-8"><span className="text-primary">{n}</span><h3 className="mt-10 text-2xl font-semibold">{t}</h3><p className="mt-5 text-sm leading-7 text-muted-foreground">{b}</p></article>)}</div><p className="mt-6 text-xs text-muted-foreground">개별 계약의 범위와 조건은 프로젝트 협의 단계에서 서면으로 확인합니다.</p></section>
  <section className="bg-muted"><div className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><p className="eyebrow text-primary">HOW WE WORK</p><h2 className="mt-5 text-4xl font-semibold md:text-5xl">승인 대기 없는 5단계</h2><div className="mt-14">{steps.map(([n,t,b])=><div key={n} className="grid gap-4 border-t border-border py-6 md:grid-cols-[80px_240px_1fr]"><span className="text-primary">STEP {n}</span><b>{t}</b><p className="text-sm text-muted-foreground">{b}</p></div>)}</div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['무역상 중개 견적','현지 브로커 확인','본사 승인 회신 대기','단계별 마진 가산'].map(x=><p key={x} className="border border-border p-4 text-sm text-muted-foreground"><X className="mr-2 inline text-primary" size={14}/>{x}</p>)}</div></div></section>
  <ContactBand/>
</SiteShell>}