/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as BrandsForestHouseRouteImport } from './routes/brands.forest-house'
import { Route as BrandsForestHouseProductsRouteImport } from './routes/brands.forest-house-products'
import { Route as BrandsHuanqiuStoneRouteImport } from './routes/brands.huanqiu-stone'
import { Route as BrandsHuanqiuStoneProductsRouteImport } from './routes/brands.huanqiu-stone-products'
import { Route as BrandsIntcoDecorRouteImport } from './routes/brands.intco-decor'
import { Route as BrandsIntcoDecorProductsRouteImport } from './routes/brands.intco-decor-products'
import { Route as BrandsJinchengGlassRouteImport } from './routes/brands.jincheng-glass'
import { Route as BrandsLionKingRouteImport } from './routes/brands.lion-king'
import { Route as BrandsShuofengRouteImport } from './routes/brands.shuofeng'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsForestHouseRoute = BrandsForestHouseRouteImport.update({
  id: '/brands/forest-house',
  path: '/brands/forest-house',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsForestHouseProductsRoute =
  BrandsForestHouseProductsRouteImport.update({
    id: '/brands/forest-house-products',
    path: '/brands/forest-house-products',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandsHuanqiuStoneRoute = BrandsHuanqiuStoneRouteImport.update({
  id: '/brands/huanqiu-stone',
  path: '/brands/huanqiu-stone',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsHuanqiuStoneProductsRoute =
  BrandsHuanqiuStoneProductsRouteImport.update({
    id: '/brands/huanqiu-stone-products',
    path: '/brands/huanqiu-stone-products',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandsIntcoDecorRoute = BrandsIntcoDecorRouteImport.update({
  id: '/brands/intco-decor',
  path: '/brands/intco-decor',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIntcoDecorProductsRoute =
  BrandsIntcoDecorProductsRouteImport.update({
    id: '/brands/intco-decor-products',
    path: '/brands/intco-decor-products',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandsJinchengGlassRoute = BrandsJinchengGlassRouteImport.update({
  id: '/brands/jincheng-glass',
  path: '/brands/jincheng-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsLionKingRoute = BrandsLionKingRouteImport.update({
  id: '/brands/lion-king',
  path: '/brands/lion-king',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsShuofengRoute = BrandsShuofengRouteImport.update({
  id: '/brands/shuofeng',
  path: '/brands/shuofeng',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/brands/forest-house': typeof BrandsForestHouseRoute
  '/brands/forest-house-products': typeof BrandsForestHouseProductsRoute
  '/brands/huanqiu-stone': typeof BrandsHuanqiuStoneRoute
  '/brands/huanqiu-stone-products': typeof BrandsHuanqiuStoneProductsRoute
  '/brands/intco-decor': typeof BrandsIntcoDecorRoute
  '/brands/intco-decor-products': typeof BrandsIntcoDecorProductsRoute
  '/brands/jincheng-glass': typeof BrandsJinchengGlassRoute
  '/brands/lion-king': typeof BrandsLionKingRoute
  '/brands/shuofeng': typeof BrandsShuofengRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/brands/forest-house': typeof BrandsForestHouseRoute
  '/brands/forest-house-products': typeof BrandsForestHouseProductsRoute
  '/brands/huanqiu-stone': typeof BrandsHuanqiuStoneRoute
  '/brands/huanqiu-stone-products': typeof BrandsHuanqiuStoneProductsRoute
  '/brands/intco-decor': typeof BrandsIntcoDecorRoute
  '/brands/intco-decor-products': typeof BrandsIntcoDecorProductsRoute
  '/brands/jincheng-glass': typeof BrandsJinchengGlassRoute
  '/brands/lion-king': typeof BrandsLionKingRoute
  '/brands/shuofeng': typeof BrandsShuofengRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/brands/forest-house': typeof BrandsForestHouseRoute
  '/brands/forest-house-products': typeof BrandsForestHouseProductsRoute
  '/brands/huanqiu-stone': typeof BrandsHuanqiuStoneRoute
  '/brands/huanqiu-stone-products': typeof BrandsHuanqiuStoneProductsRoute
  '/brands/intco-decor': typeof BrandsIntcoDecorRoute
  '/brands/intco-decor-products': typeof BrandsIntcoDecorProductsRoute
  '/brands/jincheng-glass': typeof BrandsJinchengGlassRoute
  '/brands/lion-king': typeof BrandsLionKingRoute
  '/brands/shuofeng': typeof BrandsShuofengRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/brands/forest-house'
    | '/brands/forest-house-products'
    | '/brands/huanqiu-stone'
    | '/brands/huanqiu-stone-products'
    | '/brands/intco-decor'
    | '/brands/intco-decor-products'
    | '/brands/jincheng-glass'
    | '/brands/lion-king'
    | '/brands/shuofeng'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/brands/forest-house'
    | '/brands/forest-house-products'
    | '/brands/huanqiu-stone'
    | '/brands/huanqiu-stone-products'
    | '/brands/intco-decor'
    | '/brands/intco-decor-products'
    | '/brands/jincheng-glass'
    | '/brands/lion-king'
    | '/brands/shuofeng'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/brands/forest-house'
    | '/brands/forest-house-products'
    | '/brands/huanqiu-stone'
    | '/brands/huanqiu-stone-products'
    | '/brands/intco-decor'
    | '/brands/intco-decor-products'
    | '/brands/jincheng-glass'
    | '/brands/lion-king'
    | '/brands/shuofeng'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  BrandsForestHouseRoute: typeof BrandsForestHouseRoute
  BrandsForestHouseProductsRoute: typeof BrandsForestHouseProductsRoute
  BrandsHuanqiuStoneRoute: typeof BrandsHuanqiuStoneRoute
  BrandsHuanqiuStoneProductsRoute: typeof BrandsHuanqiuStoneProductsRoute
  BrandsIntcoDecorRoute: typeof BrandsIntcoDecorRoute
  BrandsIntcoDecorProductsRoute: typeof BrandsIntcoDecorProductsRoute
  BrandsJinchengGlassRoute: typeof BrandsJinchengGlassRoute
  BrandsLionKingRoute: typeof BrandsLionKingRoute
  BrandsShuofengRoute: typeof BrandsShuofengRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/forest-house': {
      id: '/brands/forest-house'
      path: '/brands/forest-house'
      fullPath: '/brands/forest-house'
      preLoaderRoute: typeof BrandsForestHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/forest-house-products': {
      id: '/brands/forest-house-products'
      path: '/brands/forest-house-products'
      fullPath: '/brands/forest-house-products'
      preLoaderRoute: typeof BrandsForestHouseProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/huanqiu-stone': {
      id: '/brands/huanqiu-stone'
      path: '/brands/huanqiu-stone'
      fullPath: '/brands/huanqiu-stone'
      preLoaderRoute: typeof BrandsHuanqiuStoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/huanqiu-stone-products': {
      id: '/brands/huanqiu-stone-products'
      path: '/brands/huanqiu-stone-products'
      fullPath: '/brands/huanqiu-stone-products'
      preLoaderRoute: typeof BrandsHuanqiuStoneProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/intco-decor': {
      id: '/brands/intco-decor'
      path: '/brands/intco-decor'
      fullPath: '/brands/intco-decor'
      preLoaderRoute: typeof BrandsIntcoDecorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/intco-decor-products': {
      id: '/brands/intco-decor-products'
      path: '/brands/intco-decor-products'
      fullPath: '/brands/intco-decor-products'
      preLoaderRoute: typeof BrandsIntcoDecorProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/jincheng-glass': {
      id: '/brands/jincheng-glass'
      path: '/brands/jincheng-glass'
      fullPath: '/brands/jincheng-glass'
      preLoaderRoute: typeof BrandsJinchengGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/lion-king': {
      id: '/brands/lion-king'
      path: '/brands/lion-king'
      fullPath: '/brands/lion-king'
      preLoaderRoute: typeof BrandsLionKingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/shuofeng': {
      id: '/brands/shuofeng'
      path: '/brands/shuofeng'
      fullPath: '/brands/shuofeng'
      preLoaderRoute: typeof BrandsShuofengRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  BrandsForestHouseRoute: BrandsForestHouseRoute,
  BrandsForestHouseProductsRoute: BrandsForestHouseProductsRoute,
  BrandsHuanqiuStoneRoute: BrandsHuanqiuStoneRoute,
  BrandsHuanqiuStoneProductsRoute: BrandsHuanqiuStoneProductsRoute,
  BrandsIntcoDecorRoute: BrandsIntcoDecorRoute,
  BrandsIntcoDecorProductsRoute: BrandsIntcoDecorProductsRoute,
  BrandsJinchengGlassRoute: BrandsJinchengGlassRoute,
  BrandsLionKingRoute: BrandsLionKingRoute,
  BrandsShuofengRoute: BrandsShuofengRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
